version: '3.8'

services:
  postgres_db:
    image: postgres:15-alpine
    container_name: isaac_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: suasenha
      POSTGRES_DB: isaac_db
    ports:
      - "5433:5432"
    volumes:
      # Agora ele pega a pasta toda! Tudo que for .sql vai rodar.
      - ./scripts:/docker-entrypoint-initdb.d